test/response/fetch.test.ts
test/response/http.test.ts
test/response/https.test.ts

Fixes jest-environment typo

---

src/XMLHttpRequest/XMLHttpRequest/XMLHttpRequestOverride.ts
src/utils/cleanUrl.test.ts
src/utils/cleanUrl.ts
test/response/xhr.test.ts

XHR: Supports relative request URL

---

package.json
src/XMLHttpRequest/XMLHttpRequest/createXMLHttpRequestOverride.ts
src/http/ClientRequest/ClientRequestOverride.ts
test/intercept/fetch/fetch.test.ts
yarn.lock

Converts ClientRequest headers to lowercase

---

src/RequestInterceptor.ts
src/XMLHttpRequest/XMLHttpRequest/createXMLHttpRequestOverride.ts
src/XMLHttpRequest/override.ts
src/http/ClientRequest/ClientRequestOverride.ts
src/http/ClientRequest/normalizeHttpRequestParams.ts
src/http/override.ts
src/utils/getUrlByRequestOptions.ts

Adds request method and URL to the debugging info

---

tsconfig.json

Enables source maps in the library build

---

src/utils/getUrlByRequestOptions.ts

Refactors the `getUrlByRequestOptions` function to it's easier to read through.
- Follow up of #62, #64

getUrlByRequestOptions: Breaks into smaller functions

---

README.md
src/createInterceptor.ts
src/interceptors/ClientRequest/createClientRequestOverride.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
src/interceptors/fetch/index.ts
src/presets/browser.ts
test/events/response.node.test.ts
test/events/response.test.ts
test/helpers.ts
test/intercept/XMLHttpRequest/XMLHttpRequest.test.ts
test/intercept/fetch/fetch.test.ts
test/intercept/http/http.get.test.ts
test/intercept/http/http.request.test.ts
test/intercept/https/https.get.test.ts
test/intercept/https/https.request.test.ts
test/regressions/http-post-body.test.ts
test/regressions/http-supertest-post.test.ts

- Renames Ismophric->Isomorphic
- Adds a browser preset
- Updates README

Fetch interceptor additions

---

src/interceptors/ClientRequest/utils/normalizeHttpRequestParams.test.ts
src/interceptors/ClientRequest/utils/normalizeHttpRequestParams.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
src/interceptors/XMLHttpRequest/utils/createEvent.ts
test/intercept/XMLHttpRequest/XMLHttpRequest.browser.runtime.js
test/intercept/fetch/fetch.body.runtime.js
test/intercept/fetch/fetch.intercept.runtime.js
test/regressions/http-post-body.test.ts
test/regressions/xhr-timeout.test.ts
test/response/fetch.browser.runtime.js
test/response/xhr.browser.runtime.js
test/webpack.config.ts

Updates aliases and GitHub issues to be representative of the new package name

Update aliases from nri -> @mswjs/interceptors

---

src/interceptors/ClientRequest/utils/normalizeHttpRequestParams.test.ts
src/interceptors/ClientRequest/utils/normalizeHttpRequestParams.ts

Fixes https://github.com/mswjs/msw/issues/705

Fix condition to assume an `URL` object

---

src/interceptors/ClientRequest/createClientRequestOverride.ts
src/interceptors/ClientRequest/index.ts

- Fixes https://github.com/mswjs/msw/issues/710 (memory leak in MSW)
Discussion on this can be found at issue https://github.com/mswjs/interceptors/issues/115

Removes ClientRequest monkey patching

---

src/interceptors/ClientRequest/createClientRequestOverride.ts
src/interceptors/ClientRequest/index.ts
src/interceptors/ClientRequest/utils/normalizeHttpRequestParams.ts
src/utils/cloneObject.test.ts
src/utils/cloneObject.ts
test/regressions/https-original-url.test.ts
test/regressions/xhr-timeout.test.ts
test/response/fetch.test.ts

- Fixes #131 
- Fixes https://github.com/mswjs/msw/issues/700
- Fixes #133

Fixes the call signature of the original "https.request"

---

package.json
src/remote.ts
yarn.lock

Replaces the internal `invariant` utility with the `outvariant` package.

Uses "outvariant" for invariants

---

src/interceptors/ClientRequest/utils/getIncomingMessageBody.ts
test/helpers.ts
test/performance/http.test.ts
test/webpack.config.ts

- Fixes #139
- Related to https://github.com/mswjs/msw/issues/785

getIncomingMessageBody: Removes event listeners to prevent memory leak

---

src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
test/response/xhr.test.ts

XMLHttpRequest: Adds the forbidden "cookie" response header test

---

package.json
yarn.lock

- Related to https://github.com/mswjs/msw/issues/844

Bumps "outvariant" to 1.1.0

---

package.json
yarn.lock

- Related to https://github.com/open-draft/outvariant/pull/2

Updates "outvariant" to 1.2.0

---

package.json
test/intercept/fetch/fetch.clone.browser.test.ts
test/intercept/fetch/fetch.clone.runtime.js
yarn.lock

deps: remove "chai"

---

src/interceptors/ClientRequest/NodeClientRequest.ts

The dynamic number of `ClientRequest.prototype.end` args must be accounted for. 
The number of arguments may be variable but their order matters. To preserve the behavior of the class when given incomplete arguments, they must be spread dynamically. This also means the correct migration from the previous `ClientRequestOverride` implementation. 
https://github.com/mswjs/interceptors/blob/377a75e7304b9f604ccfe036a7d36bfd5a9a5489/src/interceptors/ClientRequest/createClientRequestOverride.ts#L322-L333
https://github.com/mswjs/interceptors/blob/fa8845f4ea4e367f43c88f4bdfd7c1331481f505/src/interceptors/ClientRequest/NodeClientRequest.ts#L161-L164

fix(NodeClientRequest): spread dynamic number of "end" args

---

.github/FUNDING.yml

Use the [MSW GitHub Sponsors profile](https://github.com/sponsors/mswjs) for the "Sponsor" button.

chore: add GitHub sponsors

---

.github/workflows/ci.yaml
commitlint.config.js
package.json
release.config.js
simple-git-hooks.js
yarn.lock

Use semantic release, conventional commits, and commitlint.

chore: use semantic release

---

package.json
src/createInterceptor.ts
src/interceptors/ClientRequest/NodeClientRequest.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
src/interceptors/fetch/index.ts
src/remote.ts
src/utils/toIsoResponse.test.ts
src/utils/toIsoResponse.ts
test/helpers.ts
test/modules/XMLHttpRequest/intercept/XMLHttpRequest.test.ts
test/modules/fetch/response/fetch.browser.test.ts
yarn.lock

Just a dependency name change.

fix(deps): use "headers-polyfill"

---

package.json
test/modules/XMLHttpRequest/compliance/xhr-no-response-headers.test.ts
yarn.lock

fix(xhr): support original responses without any headers

---

.github/workflows/ci.yml

Dependency to https://github.com/mswjs/msw/pull/1160

chore: use both node 14 and 16 for ci

---

src/interceptors/ClientRequest/NodeClientRequest.ts
test/modules/http/compliance/http-req-write.test.ts

fix(ClientRequest): skip callback when writing empty chunk

---

src/interceptors/fetch/index.ts

To follow up the issue: https://github.com/mswjs/msw/issues/1226#issuecomment-1121212623

Rewrite global.fetch instead of window.fetch

---

src/interceptors/ClientRequest/NodeClientRequest.ts

- Fixes https://github.com/mswjs/msw/issues/1218

fix(ClientRequest): add "EAI_AGAIN" to suppressed errors list

---

README.md

- Closes https://github.com/mswjs/interceptors/issues/246

docs: clarify that only browser fetch is supported

---

src/index.ts

Makes the consumption of the buffer utils easier.

fix: export "encodeBuffer" and "decodeBuffer" utils

---

package.json

fix: add "@types/debug" as a dependency

---

README.md

docs: add ".apply()" to readme examples

---

test/third-party/supertest.test.ts

test(supertest): add event listener tests

---

tsconfig.json

fix: build library to ES6

---

src/interceptors/fetch/index.ts

fix(fetch): do not optimistically rely on "location" in fetch interceptor

---

src/interceptors/fetch/index.ts

- Backport for #356 
- Fixes https://github.com/mswjs/msw/issues/1557

fix(fetch): treat handler exceptions as TypeError

---

README.md
package.json
presets/browser/package.json
presets/node/package.json
src/BatchInterceptor.ts
src/Interceptor.ts
src/interceptors/ClientRequest/index.ts
src/interceptors/XMLHttpRequest/index.ts
src/presets/browser.ts
src/presets/node.ts
test/features/presets/browser-preset.browser.test.ts
test/features/presets/browser-preset.runtime.js
test/features/presets/node-preset.test.ts
tsup.config.ts

fix: export node and browser presets

---

src/Interceptor.ts
src/interceptors/ClientRequest/NodeClientRequest.test.ts
src/interceptors/ClientRequest/http.request.ts
src/interceptors/ClientRequest/utils/createRequest.test.ts
src/interceptors/ClientRequest/utils/getIncomingMessageBody.ts
src/interceptors/ClientRequest/utils/normalizeClientRequestArgs.ts
src/interceptors/ClientRequest/utils/normalizeClientRequestEndArgs.ts
src/interceptors/ClientRequest/utils/normalizeClientRequestWriteArgs.ts
src/utils/AsyncEventEmitter.ts
src/utils/cloneObject.ts
src/utils/debug.ts
src/utils/getUrlByRequestOptions.ts

Fix for #350 
Changes the imports, so they handle the CommonJS exports from the "debug" package.

fix: correctly imports commonjs "debug" package

---

package.json
yarn.lock

Related to https://github.com/mswjs/msw/pull/1436#issuecomment-1478101323

fix: update "strict-event-emitter" to 0.5.0

---

package.json
src/BatchInterceptor.ts
src/Interceptor.ts
src/RemoteHttpInterceptor.ts
src/interceptors/ClientRequest/NodeClientRequest.test.ts
src/interceptors/ClientRequest/NodeClientRequest.ts
src/interceptors/ClientRequest/http.request.ts
src/interceptors/ClientRequest/index.ts
src/interceptors/ClientRequest/utils/createRequest.test.ts
src/interceptors/ClientRequest/utils/getIncomingMessageBody.ts
src/interceptors/ClientRequest/utils/normalizeClientRequestArgs.ts
src/interceptors/ClientRequest/utils/normalizeClientRequestEndArgs.ts
src/interceptors/ClientRequest/utils/normalizeClientRequestWriteArgs.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestController.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestProxy.ts
src/interceptors/XMLHttpRequest/index.ts
src/interceptors/fetch/index.ts
src/utils/AsyncEventEmitter.ts
src/utils/cloneObject.ts
src/utils/debug.ts
src/utils/getUrlByRequestOptions.ts
yarn.lock

- Migrate to https://github.com/open-draft/logger
- Related https://github.com/mswjs/msw/pull/1436 (to improve the ESM support)

fix: migrate from "debug" to "@open-draft/logger"

---

src/interceptors/ClientRequest/NodeClientRequest.test.ts
src/interceptors/ClientRequest/NodeClientRequest.ts

- Required by #462 
- Required by #453

chore(ClientRequest): add internal "isRequestSent" flag

---

src/index.ts
src/interceptors/ClientRequest/utils/createResponse.test.ts
src/interceptors/ClientRequest/utils/createResponse.ts
src/interceptors/XMLHttpRequest/utils/createResponse.ts
src/utils/responseUtils.ts

- Related to https://github.com/mswjs/msw/pull/1894

fix: export a "isResponseWithoutBody" utility

---

src/crypto-shim.ts
src/interceptors/ClientRequest/NodeClientRequest.test.ts
src/interceptors/ClientRequest/NodeClientRequest.ts
src/interceptors/WebSocket/WebSocketClientConnection.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestController.ts
src/interceptors/fetch/index.ts
src/utils/uuid.ts
test/modules/http/regressions/http-socket-timeout.vitest.config.js
test/vitest.config.js
test/vitest.setup.crypto.ts
test/webpack.config.ts
tsup.config.ts
vitest.config.mjs

fix: use global "crypto.randomUUID()"

---

src/createRequestId.test.ts
src/createRequestId.ts
src/crypto-shim.ts
src/index.ts
src/interceptors/ClientRequest/NodeClientRequest.ts
src/interceptors/WebSocket/WebSocketClientConnection.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestController.ts
src/interceptors/fetch/index.ts
src/randomId.ts
test/features/events/request.test.ts
test/helpers.ts
test/modules/WebSocket/compliance/websocket.connection.test.ts
test/modules/XMLHttpRequest/features/events.test.ts
test/modules/XMLHttpRequest/intercept/XMLHttpRequest.test.ts
test/modules/fetch/intercept/fetch.request.test.ts
test/modules/fetch/intercept/fetch.test.ts
test/modules/http/intercept/http.get.test.ts
test/modules/http/intercept/http.request.test.ts
test/modules/http/intercept/https.get.test.ts
test/modules/http/intercept/https.request.test.ts
test/modules/http/regressions/http-socket-timeout.vitest.config.js
test/vitest.config.js
test/vitest.setup.crypto.ts
test/webpack.config.ts
tsup.config.ts
vitest.config.mjs

- Reported in https://github.com/mswjs/msw/issues/2111

fix: drop "crypto.randomUUID()" in favor of "createRequestId()"

---

README.md

docs: add "Error handling" section to README

---

src/interceptors/WebSocket/WebSocketServerConnection.ts
test/modules/WebSocket/compliance/websocket.server.events.test.ts

- The `error` event is now correctly emitted on the `server` connection object.
- Fixes the issue where the `close` event listener wasn't correctly removed for the `handlRealClose` listener (using `AbortController` now). That resulted in the `close` event being dispatched _twice_ in some situations. 
> [!IMPORTANT]
> Note to myself: closing a connection with seemingly error codes _DOES NOT_ trigger the `error` event. The error event is only triggered in particular situations, such as a failed or disrupted connection (and maybe some more).

fix(WebSocket): emit "error" event on `server` connection errors

---

src/presets/node.ts
test/features/presets/node-preset.test.ts

feat: add `FetchInterceptor` to the `node` preset

---

test/features/events/response.test.ts

test: add request/response body reading test

---

src/interceptors/ClientRequest/utils/recordRawHeaders.test.ts
src/interceptors/ClientRequest/utils/recordRawHeaders.ts

- Fixes https://github.com/mswjs/interceptors/issues/631
- Related to https://github.com/mswjs/msw/issues/2269

fix(ClientRequest): prevent duplicates when recording set headers

---

src/interceptors/WebSocket/WebSocketServerConnection.ts
src/interceptors/WebSocket/utils/events.test.ts
src/interceptors/WebSocket/utils/events.ts
test/modules/WebSocket/compliance/websocket.server.close.test.ts
test/modules/WebSocket/compliance/websocket.server.events.test.ts

fix(WebSocket): make server "close" event cancelable

---

src/interceptors/WebSocket/index.ts
src/interceptors/XMLHttpRequest/index.ts
src/interceptors/fetch/index.ts
src/utils/hasConfigurableGlobal.test.ts
src/utils/hasConfigurableGlobal.ts
vitest.config.mjs

- Related to https://github.com/mswjs/msw/issues/2339

fix: skip interceptors for non-configurable globals

---

src/glossary.ts

fix: export `RequestController` type

---

src/interceptors/fetch/index.ts
test/modules/fetch/compliance/fetch-response-url.test.ts

fix(fetch): resolve relative urls against `location.href`, not `location.origin`

---

src/interceptors/ClientRequest/MockHttpSocket.ts
test/modules/WebSocket/compliance/websocket.events.test.ts
test/modules/http/compliance/http-req-get-with-body.test.ts

- Fixes https://github.com/nock/nock/issues/2826

fix(ClientRequest): allow GET requests with body

---

src/interceptors/ClientRequest/agents.ts

- Related to #675 because I always forget how requests are handled by agents.

docs: add http.Agent request flow docs
