src/RequestInterceptor.ts
src/XMLHttpRequest/XMLHttpRequest/XMLHttpRequestOverride.ts
src/http/ClientRequest/ClientRequestOverride.ts
src/index.ts
src/utils/cleanUrl.ts
src/utils/getCleanUrl.test.ts
src/utils/getCleanUrl.ts
test/helpers.ts

`getCleanUrl` is also used in `msw` for the same purpose. This logic needs to be unified across libraries to guarantee stable behavior. 
```js
import { getCleanUrl } from 'node-request-interceptor'
```

Exports "getCleanUrl" utility

---

src/XMLHttpRequest/XMLHttpRequest/XMLHttpRequestOverride.ts
src/glossary.ts
src/http/ClientRequest/ClientRequestOverride.ts
test/helpers.ts
test/intercept/XMLHttpRequest/XMLHttpRequest.test.ts
test/intercept/fetch/fetch.test.ts
test/intercept/http/http.get.test.ts
test/intercept/http/http.request.test.ts
test/intercept/https/https.get.test.ts
test/intercept/https/https.request.test.ts
test/response/fetch.test.ts
test/response/http.test.ts
test/response/https.test.ts
test/response/xhr.test.ts

- Intercepted `req.url` is now an instance of the `URL` class, which allows to get additional information about the URL (such as `protocol` or `searchParams`).
- Removes `req.query` as it can be accessed by `req.url.searchParams`
- Related to https://github.com/mswjs/msw/issues/158

Returns a URL instance as "req.url" value

---

tsconfig.json

- Solves the error message on the consumption's side about the inability to digest `export * from 'a'` syntax

Sets build target to "es5" to support export from

---

package.json
src/RequestInterceptor.ts
src/XMLHttpRequest/XMLHttpRequest/XMLHttpRequestOverride.ts
src/XMLHttpRequest/override.ts
test/response/axios.test.ts
yarn.lock

- XHR now explicitly sets `readyState` to DONE when a mocked response is set. This resolves the request promise in libraries like `axios`.
- XHR now triggers a `progress` event when a mocked response is set. Takes into account the length of a mocked response body.
- XHR now sets `readyState` to `HEADERS_RECEIVED` when the mocked headers are set.
- Minor adjustments to XHR-related modules
- Adds a unit test for a mocked response to `axios.get`/`axios.post`
- Fixes #13

XMLHttpRequest: resolves DONE readyState on mocked response

---

package.json
src/XMLHttpRequest/XMLHttpRequest/createXMLHttpRequestOverride.ts
src/http/ClientRequest/ClientRequestOverride.ts
src/http/ClientRequest/Socket.ts
src/http/ClientRequest/normalizeHttpRequestParams.test.ts
src/http/ClientRequest/normalizeHttpRequestParams.ts
src/utils/getRequestOptionsByUrl.ts
src/utils/urlToOptions.ts
test/helpers.ts
test/intercept/XMLHttpRequest/XMLHttpRequest.test.ts
test/intercept/fetch/fetch.test.ts
test/intercept/http/http.get.test.ts
test/intercept/http/http.request.test.ts
test/intercept/https/https.get.test.ts
test/intercept/https/https.request.test.ts
test/response/axios.test.ts
test/response/fetch.test.ts
test/response/http.test.ts
test/response/https.test.ts
test/response/xhr.test.ts

- Implemented `setNoDelay`, `setKeepAlive` and `setTimeout` methods on the `Socket` class.
- Refactored `normalizeHttpRequestParams` to have a better logical flow and to handle partial request options (those without `protocol` and `hostname`, i.e. from `supertest` requests).
- Added unit test for `normalizeHttpRequestParams`
- Fixes #19
- Implements fix for https://github.com/mswjs/msw/issues/209

Socket: Adds "setNoDelay", "setKeepAlive" and "setTimeout" methods

---

src/glossary.ts
src/http/ClientRequest/normalizeHttpRequestParams.test.ts
src/http/ClientRequest/normalizeHttpRequestParams.ts
src/utils/getUrlByRequestOptions.test.ts
src/utils/getUrlByRequestOptions.ts

- Separates the logic that creates a `URL` instance from `RequestOptions` into its own `getUrlByRequestOptions` function.
- Adds support for `options.auth` to be properly transformed into `url.username` and `url.password`.
- Adds support for inheriting `options.port` on the `URL` instance.
- Closes #21

Adds "getUrlByRequestOptions" utility

---

package.json
src/XMLHttpRequest/XMLHttpRequest/createXMLHttpRequestOverride.ts
src/http/ClientRequest/ClientRequestOverride.ts
test/helpers.ts
test/response/http.test.ts
test/response/https.test.ts
test/response/xhr.test.ts
yarn.lock

- Exception thrown in a middleware function is now gracefully handled as a request (network) error, instead of a process exception. 
- Resolves #28

Emits request error when middleware throws an exception

---

src/XMLHttpRequest/XMLHttpRequest/EventOverride.ts
src/XMLHttpRequest/XMLHttpRequest/createEvent.ts
src/XMLHttpRequest/XMLHttpRequest/createXMLHttpRequestOverride.ts
test/regressions/xhr-add-event-listener.test.ts
test/response/axios.test.ts
test/response/fetch.test.ts

- Fixes the way listener functions are invoked when attached via `addEventListener` method of `XMLHttpRequest`.
- Provides minor improvements towards event handling in `XMLHttpRequest` override class.
- Adds a regression test to cover that the `load` event attached via `addEventListener` method is properly called with the mocked response (generally, whenever XHR is done).
- Fixes https://github.com/mswjs/msw/issues/273

XHR: Invoke listeners attached via "addEventListener"

---

src/http/ClientRequest/ClientRequestOverride.ts
test/response/http.test.ts
test/response/https.test.ts

When a request is intercepted by `ClientRequestOverride` the `statusText` from `mockedResponse` was not assigned to real response.
This was the cause of an issue on [MSW](https://github.com/mswjs/msw/issues/279)
I have updated some tests checking the `responseText`

fix: status text in ClientRequestOverride

---

src/RequestInterceptor.ts
src/overrideModules.native.ts
src/overrideModules.ts

This PR will import different modules when using this package on react-native. Specifically, we don't load `overrideHttpModule`, because the `http` core module is not available on RN.

Do not load the http overwrite module in react native

---

src/XMLHttpRequest/XMLHttpRequest/EventOverride.ts
src/XMLHttpRequest/XMLHttpRequest/ProgressEventPolyfill.ts
src/XMLHttpRequest/XMLHttpRequest/createEvent.ts

- Adds the `ProgressEventPolyfill` class
- Uses the polyfill class for environments where `ProgressEvent` is not supported (i.e. React Native).
- Fixes #40

Polyfills "ProgressEvent" for unsupported environments

---

src/XMLHttpRequest/XMLHttpRequest/createXMLHttpRequestOverride.ts
test/regressions/xhr-timeout.test.ts

- Propagates callbacks (`ontimeout`, `onreadystatechange`, etc.) and event listeners (`timeout`, `error`, etc.) from the captured XHR instance to the original XHR instance.
- Propagates the `timeout` property to the original XHR, so that the request timeout is respected (i.e. when using `axios` with timeout).
- Adds respective tests.
- Originated from https://github.com/mswjs/msw/issues/284
- Fixes #7
Timeout was not passed to original request when no mock response is found.
Hope to did the right thing 😄 
Timeout should be added only if the request is async so when `this.async === true`

fix: pass timeout to request

---

.gitignore
src/XMLHttpRequest/XMLHttpRequest/createXMLHttpRequestOverride.ts
src/http/override.ts
src/utils/getUrlByRequestOptions.ts
test/intercept/XMLHttpRequest/XMLHttpRequest.test.ts

- `user` and `password` have a default value of `undefined` (previously `''`).
- `async` has a default value of `undefined` (`true` when forwarding) - (previously `false`).
- Removed parameter initializations; set default parameters on `open()`.
- In `getUrlByRequestOptions()`, check if `options.uri.protocol` is set before falling back to `DEFAULT_PROTOCOL`.
- minor cosmetic re-arrangements in ClientRequest interception (imports of http and https modules).

Fixes default forwarded XHR.open args

---

src/interceptors/ClientRequest/ClientRequestOverride.ts
src/interceptors/ClientRequest/index.ts
test/response/fetch.test.ts

The PR will fix https://github.com/mswjs/node-request-interceptor/issues/49
The problem was that on next when you make an hard refresh the old instance of `RequestInterceptor` was not cleared.
This behavior could cause an issue because the `http.ClientRequest` sometime was null.
I don't know if we should allow the user to create multiple `RequestInterceptor` on the same interceptors 🤔

fix: null value of http.ClientRequest 

---

src/interceptors/ClientRequest/ClientRequestOverride.ts
src/interceptors/ClientRequest/index.ts

Minor polishing of the `ClientRequest` class.

ClientRequest: Renames reserved "module" into "requestModule"

---

src/interceptors/ClientRequest/ClientRequestOverride.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
test/regressions/xhr-middleware-exception.test.ts

- Improves debugging of interceptors by including the actual middleware exception reference in the `debug` call.
- Ensures that NRI first emits the `error` event and then aborts the XMLHttpRequest.
- Provides a solution for https://github.com/mswjs/msw/issues/355

XMLHttpRequest: Handles middleware exceptions with error event first, then abort

---

src/utils/getUrlByRequestOptions.test.ts
src/utils/getUrlByRequestOptions.ts

In `normalizeHttpRequestParams`, the protocol is taken from the url, if there is none set in the options https://github.com/mswjs/node-request-interceptor/blob/09ec3011638131f9b06b63d106c762ab0d59d9f9/src/interceptors/ClientRequest/utils/normalizeHttpRequestParams.ts#L81
As the comment above the code states, this is to avoid an error of mismatching protocols, from this section of the node code https://github.com/nodejs/node/blob/d84f1312915fe45fe0febe888db692c74894c382/lib/_http_client.js#L142-L145
In the same code, we can see that the expected protocol comes from `this.agent`, if set and lines 125 and 140 show us that this will be the agent that is set in the options, if any exists.
Therefore in order to avoid the error when this is set, we should set the url protocol to match this one …

Resolve protocol from agent, if set

---

src/interceptors/ClientRequest/utils/normalizeHttpRequestParams.test.ts
src/interceptors/ClientRequest/utils/normalizeHttpRequestParams.ts
src/utils/getUrlByRequestOptions.test.ts
src/utils/getUrlByRequestOptions.ts
src/utils/isObject.test.ts
src/utils/isObject.ts

The `RequestOptions` object does not have any required properties, therefore we should not rely on `method` for its identification. Any object should be accepted as request options.
Since the hostname and host are also optional, we should not rely on either of them being set when constructing the URL. If node cannot find any set in hostname or host, then it defaults to `localhost` (https://github.com/nodejs/node/blob/d84f1312915fe45fe0febe888db692c74894c382/lib/_http_client.js#L163)
In order to retain parity, the default hostname should be this when creating the URL.

Allow request options to be empty and default hostname to 'localhost'

---

src/interceptors/ClientRequest/utils/normalizeHttpRequestParams.test.ts
src/interceptors/ClientRequest/utils/normalizeHttpRequestParams.ts

In addition to the WHATWG `URL` object, node js also has a legacy `Url` object, created through `url.parse`, which is accepted when creating http requests. Although this type is deprecated as of node 11, there are many packages which are using it.
This change is to allow interoperability with a wider range of packages by normalising the legacy Url to a WHATWG URL.

Support legacy Url objects

---

src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
src/utils/parseJson.test.ts
src/utils/parseJson.ts
test/helpers.ts
test/regressions/xhr-response-type.test.ts

- `XMLHttpRequest` override now respects the `req.responseType` property when setting a mocked response body as the value of the `response` property.
- Supported `responseType` values:
- `text` (default). Returns mocked response body as-is (response body is always set as text).
- `json`. Attempts to parse the mocked body as JSON. Returns `null` if parsing fails. 
- `blob`. Returns a `Blob` from the mocked response body.
- `arraybuffer`. Returns an `Unit8Array` instance from the mocked response body.
- Fixes #69

XHR: Respects "responseType" when resolving response body

---

src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
test/helpers.ts
test/regressions/xhr-response-empty-body.test.ts

- Fixes #71 
- Ensures that the body input of `XMLHttpRequest.getResponseBody` always operates on at least an empty string. Sometimes it may receive a `null` as a value, for example:
```js
// No explicit response body means "body: null" on the MSW side
res(ctx.status(403)
```
Default mocked response object declaring `body: null` as the default mocked response body value:
https://github.com/mswjs/msw/blob/33022cdecb6c979b5e2963dc88aaa2b886d7adba/src/response.ts#L46-L52

Handles empty response body in XMLHttpRequest progress event

---

test/helpers.ts
test/intercept/XMLHttpRequest/XMLHttpRequest.test.ts
test/regressions/xhr-add-event-listener.test.ts
test/regressions/xhr-response-empty-body.test.ts
test/regressions/xhr-response-type.test.ts
test/regressions/xhr-timeout.test.ts
test/response/xhr.test.ts

- Allows creation and handling of `XMLHttpRequest` as promises.
- Supports full customizability of XHR via the middleware function.
- Enforces to treat the XHR response as an actual XHR response, not a custom abstraction. Makes tests more friendly to people unfamiliar with the internal abstractions.

Adds utility to dispatch XHR as promises

---

src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
test/regressions/xhr-response-invalid-json-body.test.ts

- Fixes https://github.com/mswjs/msw/issues/487
- The `progress` event of `XMLHttpRequest` now fires only when the mocked response body was set (there's a body to load), and the coerced response body according to `responseType` is present (coercion was successful, the mocked response body is valid against the specified `responseType`). 
- The `progress` event now converts the raw mocked response body (string) into a `Buffer`, to handle various body types (string, JSON, ArrayBuffer, Blob) and determine their length.
- Adds a test to assert missing/invalid response body handling of an `XMLHttpRequest` with `responseType = 'json'`. Actual XHR behavior was taken for the reference.

XMLHttpRequest: Handles "progress" event on omni-value response body

---

src/utils/getUrlByRequestOptions.test.ts
src/utils/getUrlByRequestOptions.ts

Relates to issue on [msw #486](https://github.com/mswjs/msw/issues/486).
When port is 443 use the secure https protocol.

determine secure protocol by 443 port

---

package.json
src/interceptors/ClientRequest/ClientRequestOverride.ts
yarn.lock

1st leak comes from Debug module, when debug instances are created within a function. For more info: https://github.com/visionmedia/debug/issues/678
2nd leak is caused by `createClientRequestOverrideClass`, when `handleRequest` is called multiple times (check screenshot below). It inherits `ClientRequestOverride` from a previous `ClientRequestOverride` instance:
- `http.ClientRequest = ClientRequestOverride`
https://github.com/mswjs/node-request-interceptor/blob/728822439966cd06e67948e3bea370377d098177/src/interceptors/ClientRequest/index.ts#L33-L41
- next calls wrap `ClientRequestOverride` which wraps `ClientRequestOverride` which wraps `ClientRequestOverride` etc.
https://github.com/mswjs/node-request-interceptor/blob/728822439966cd06e67948e3bea370377d098177/src/interceptors/ClientReques …

Fix two memory leaks

---

package.json
src/RequestInterceptor.ts
src/glossary.ts
src/index.ts
src/interceptors/ClientRequest/ClientRequestOverride.ts
src/interceptors/ClientRequest/index.ts
src/interceptors/ClientRequest/utils/getIncomingMessageBody.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
src/interceptors/XMLHttpRequest/index.ts
test/events/response.node.test.ts
test/events/response.test.ts
test/helpers.ts
yarn.lock

- Closes #25
- Enables https://github.com/mswjs/msw/pull/482
It's now possible to listen to any response (original/mocked) using the `on` method of the interceptor:
```js
const interceptor = new RequestInterceptor(...)
interceptor.on('response', (req, res) => {
req // intercepted request instance
res // real/mocked response coerced to the `MockedResponse` object shape
})
```

Adds a "response" event

---

src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
test/regressions/xhr-propagate-headers.test.ts

- When the request is not mocked, the original request is made. This PR will fix an issue where client headers were not forwarded to the server

fix: propagate headers when making original XMLHttpRequest

---

src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
test/compliance/XMLHttpRequest.test.ts

TypeScript's `interface XMLHttpRequest` in lib.dom.d.ts requires these properties to exist as static and instance properties. I've added the static properties here, but I'm unsure how to enforce them against the type.
https://github.com/microsoft/TypeScript/blob/2428ade1a91248e847f3e1561e31a9426650efee/lib/lib.dom.d.ts#L18806-L18810
https://github.com/microsoft/TypeScript/blob/2428ade1a91248e847f3e1561e31a9426650efee/lib/lib.dom.d.ts#L18817-L18825
Fixes #78

add static copies of readyState values

---

src/glossary.ts
src/interceptors/ClientRequest/ClientRequestOverride.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts

- Fixes #82
- The `response` event now returns a full `MockedResponse` object, not partial. 
- `MockedResponse.body` is now properly annotated as `string | undefined` (the lack of body is represented as `undefined`).
- `200` is used is a fallback `IncomingMessage.statusCode` and `OK` is used as a fallback for `IncomingMessage.statusText`, however, those fallbacks are only to satisfy TypeScript, as both properties are _set and present_ once the response headers are written (it's possible to access them before the headers are written, and _then_ they are undefined).

Events: Ensures full "MockedResponse" instance in the callback

---

README.md

This PR corrects the lib file resolve path in README, to avoid confusions.
see https://github.com/mswjs/node-request-interceptor/issues/68#issuecomment-772552694

correct the lib file resolve path in README

---

src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
test/regressions/xhr-response-header-case-sensitivity.test.ts

I came across a problem when using MSW in testing: the component under test has a dependency that makes API calls (authentication) and inspects the "Content-Type" response header (note the casing), but the value of this header was always null. I traced this to the XMLHttpRequestOverride's `getResponseHeader` function which evaluated "Content-Type" (the passed in header name) against "content-type" (the actual header name in the response), thereby failing and returning null.
This PR updates the XHR `getResponseHeader` function to normalise the passed in header name and the response headers to lowercase when evaluating equality. This looks to be similar behaviour to [jsdom's implementation](https://github.com/jsdom/jsdom/blob/5279cfda5fe4d52f04b2eb6a801c98d81f9b55da/lib/jsdom/living/xhr/xhr- …

XMLHttpRequest `getResponseHeader` case sensitivity

---

package.json
src/interceptors/ClientRequest/createClientRequestOverride.ts
src/interceptors/ClientRequest/index.ts
src/interceptors/ClientRequest/utils/normalizeHttpRequestParams.test.ts
src/interceptors/ClientRequest/utils/normalizeHttpRequestParams.ts
src/utils/getUrlByRequestOptions.ts
test/intercept/http/http.get.test.ts
test/intercept/http/http.request.test.ts
test/intercept/https/https.get.test.ts
test/intercept/https/https.request.test.ts
yarn.lock

- Fixes https://github.com/mswjs/msw/issues/632
- Fixes #67 
- Closes #66
- `normalizeHttpRequestParams` function now accepts the `defaultProtocol: string` argument that represents the default protocol associated with the request module (`http`/`https`). 
- **Only if the `protocol` isn't otherwise provided** (i.e. in `options.protocol`, or `URL.protocol`), request params normalization infers the `defaultProtocol`.

ClientRequest: Infers protocol from the request module (defaultProtocol) if not provided

---

src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
test/response/axios.test.ts

As for the mocked request also bypass request should have the readyState set to 4 (DONE) when a response is received
Fixes https://github.com/mswjs/msw/issues/636

fix: set readyState to 4 (DONE) on bypassed response

---

src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
test/compliance/XMLHttpRequest.test.ts

- Fixes https://github.com/mswjs/headers-utils/issues/9
- Removes an extra space in the headers string when calling `XMLHttpRequest.getAllResponseHeaders()` method.
- Adds a compliance test for `.getAllResponseHeaders()` method.

XMLHttpRequest: Removes an extra space in ".getAllResponseHeaders"

---

src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
src/interceptors/XMLHttpRequest/utils/bufferFrom.test.ts
src/interceptors/XMLHttpRequest/utils/bufferFrom.ts
src/interceptors/XMLHttpRequest/utils/createEvent.test.ts
src/interceptors/XMLHttpRequest/utils/createEvent.ts
test/helpers.ts
test/intercept/XMLHttpRequest/XMLHttpRequest.browser.runtime.js
test/intercept/XMLHttpRequest/XMLHttpRequest.browser.test.ts
test/response/xhr.browser.runtime.js
test/response/xhr.browser.test.ts

- Follow-up to #93 
- Adds in-browser tests for XMLHttpRequest interception and response mocking.
- Uses the env-agnostic `bufferFrom` utility instead of `Buffer.from()` that's available only in Node.js.
- Adds tests for the `createEvent` function.
We don't need to use the native `window.Event` because it forbids setting the `target`, which in the case of `XMLHttpRequestOverride` should be the overridden class. That's one of the reasons we have the `EventPolyfill` because it allows setting a custom event target in the class constructor.

Supports XMLHttpRequest interception in a browser

---

README.md
package.json

This package is no longer Node.js-specific after the introduction of the `fetch` interception (#93). The "node" part in the name may be confusing.

Renames the package to "@mswjs/interceptors"

---

src/interceptors/ClientRequest/createClientRequestOverride.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
test/events/request.test.ts

Fix for https://github.com/mswjs/interceptors/issues/111.

Emits the "request" event in the ClientRequest and XMLHttpRequest overrides

---

package.json
src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
test/regressions/xhr-response-xml-body.test.ts
yarn.lock

Prior to this PR, `responseXML` was always set to `null`, even if the `Content-Type: */xml` header was present. This PR updates the XMLHttpRequest interceptor to return `responseXML` when XML is returned by the resolver.
I originally opened https://github.com/mswjs/msw/issues/715 for this issue before I understood that this repo was a better location for the fix.

fix: set responseXML when resolver returns xml

---

src/interceptors/ClientRequest/createClientRequestOverride.ts

Jest 27 removes the `setImmediate`-global so replaced it with setTimeout with a 0 delay
fixes #123

fix: add support for Jest 27

---

src/interceptors/ClientRequest/createClientRequestOverride.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
src/interceptors/fetch/index.ts
src/utils/toIsoResponse.test.ts
src/utils/toIsoResponse.ts

Currently, all override classes normalize a `MockedResponse` object into an `IsomorphicResponse` object by listing the same fallback values logic repeatedly. This change aims to have a single utility to perform said normalization.
- Adds the `toIsoResponse` utility that convers a (partial) mocked response into an `IsomorphicResponse` (adds fallback values).
- Adjusts the interceptor classes to use the said utility.

Adds the "toIsoResponse" helper function

---

README.md
src/createInterceptor.ts
src/index.ts
src/interceptors/ClientRequest/createClientRequestOverride.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
src/interceptors/fetch/index.ts
src/remote.ts
src/utils/uuid.ts
test/features/remote/child-process.test.ts
test/features/remote/child.js
test/features/remote/remote.test.ts

Since this library patches the request-issuing modules in the _current process_, there is no way to enable request interception in a _child_ process (i.e. when testing a running application). An alternative has been suggested previously to enable the interception on the application's side, for example:
```js
// src/index.js
createInterceptors({ ... }).apply()
```
However, this implies that:
- Response resolution logic needs to be described in the app (possibly on runtime via environmental variables).
- A single test cannot affect the response resolution logic, as the application and a test live in separate universes.
This change aims to support request interception in a child process by using the IPC between the parent (test) and the child (spawned application) processes and signaling …

Supports request interception in a ChildProcess

---

src/interceptors/ClientRequest/polyfills/SocketPolyfill.ts
test/regressions/http-timeout.test.ts
test/regressions/http-timeout.ts

Noticed that my tests hanged in Jest with
```
Jest did not exit one second after the test run has completed.
This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```
when I has using the Elasticsearch client with msw passthrough. It used 30 second timeout. 
After comparing to the real socket in node.js core I noticed it uses unreffed timers so I guess it should be used here too. At least this fixes my hanging test issue. Although I'm not sure why the SocketPolyfill is in play with the passthrough requests.
Node.js source links:
https://github.com/nodejs/node/blob/7766b3853a5a521fd4e8994fab5e9d4b6c83ccba/lib/net.js#L458 …

Unref SocketPolyfill#setTimeout()

---

src/interceptors/ClientRequest/utils/getIncomingMessageBody.test.ts
src/interceptors/ClientRequest/utils/getIncomingMessageBody.ts

- Fixes #109 
- `getIncomingMessageBody` will now handle the gzip compression to prevent the corruption of compressed response bodies. 
- Adds previously missing unit tests for the `getIncomingMessageBody` function.

Supports gzip content-encoding when retrieving the IncomingMessage body

---

package.json
src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
test/regressions/xhr-response-xml-body.test.ts
yarn.lock

This is to fix the xmldom security vulnerability - closes #145 
Per [the xmldom issue](https://github.com/xmldom/xmldom/issues/271), xmldom is now published at @xmldom/xmldom.

Ugrade xmldom to use latest version at new location at @xmldom/xmldom

---

src/interceptors/ClientRequest/NodeClientRequest.ts
src/interceptors/ClientRequest/utils/cloneIncomingMessage.test.ts
src/interceptors/ClientRequest/utils/cloneIncomingMessage.ts
src/interceptors/ClientRequest/utils/getIncomingMessageBody.test.ts
src/interceptors/ClientRequest/utils/getIncomingMessageBody.ts
src/interceptors/ClientRequest/utils/normalizeClientRequestArgs.ts
test/events/request.test.ts
test/events/response.node.test.ts
test/events/response.test.ts
test/jest.node.config.js
test/regressions/http-incoming-message-clone.test.ts

- Fixes https://github.com/mswjs/msw/issues/941
- Fixes #161
- Uses an internal `cloneIncomingMessage` function that pipes a given IncomingMessage to a `PassThrough` stream. It also copies all the message's properties and symbols to ensure an identical copy for whichever code may rely on it (piped stream does not have response properties like `statusCode` or `rawHeaders`).
- Fixes `getIncomingMessageBody` test so they won't silently swallow assertion failures.
- Adds a regression test to capture the Stripe use-case (see https://github.com/mswjs/msw/issues/941)

fix(NodeClientRequest): clone "response" to allow reading its body twice

---

test/regressions/http-concurrent-same-host.test.ts

- Closes #2
- Adds an integration test for multiple concurrent `http.get` calls to the same host. Ensures requests do not get mixed up (each preserves its headers).

test: assert concurrent same-host requests

---

test/compliance/XMLHttpRequest/events-order.test.ts
test/compliance/XMLHttpRequest/request-headers.test.ts
test/events/request.test.ts
test/integrations/got.test.ts
test/intercept/fetch/fetch.test.ts
test/performance/http.test.ts
test/regressions/http-post-body.test.ts
test/regressions/http-timeout.ts
test/regressions/https-original-url.test.ts
test/regressions/xhr-propagate-headers.test.ts
test/regressions/xhr-response-header-case-sensitivity.test.ts
test/response/axios.test.ts
test/response/fetch.browser.test.ts
test/response/fetch.test.ts
test/response/http.test.ts
test/response/https-callback.test.ts
test/response/https.test.ts
test/response/xhr.test.ts

When using a test HTTP server, always call it `httpServer` in tests.

chore: use "httpServer" namespace consistently

---

src/interceptors/ClientRequest/NodeClientRequest.test.ts
src/interceptors/ClientRequest/NodeClientRequest.ts
src/interceptors/ClientRequest/utils/normalizeClientRequestWriteArgs.ts
test/regressions/http-concurrent-different-response-source.test.ts

- Fixes #168 
- Captures and suppresses certain ClientRequest errors (i.e. `ECONNREFUSED`). This prevents the request instance from being destroyed. 
- Replays the first captured error while constructing the ClientRequest once using the "bypass" response source.
I've concluded my initial attempt to provide a custom `Agent.createConnection` to be unnecessary. While it's possible to prevent socket connection that way, it's problematic to let the ClientRequest believe the connection was made (otherwise it won't function properly). Preventing the socket connection altogether is also undesired as it effectively means that we'd have to _recreate_ that connection from scratch once using the "bypass" response source. This is precisely what makes Node.js request interception slow when using MSW …

fix(NodeClientRequest): suppress connection errors for mocked requests

---

src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts

change `upload` to object to avoid `upload.onprogress` runtime error.
some npm file upload deps use `xhr.upload.onprogress = () => {}` for pogress reporting. 
Changing `upload` to an object will at least **_temporarily_** avoid this runtime error and unblock teams on writing tests.
Reference:
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/upload

fix: change upload property to object

---

package.json

This is the real fix for https://github.com/mswjs/msw/issues/1030 which can be closed...
- Fixes https://github.com/mswjs/msw/issues/1030

fix: Publish sources (#196)

---

package.json

Our current required `node` version is rather strict. We do not rely on features from `12.20` directly. Any 12.x release should be compatible.

fix: set required node to "12.x"

---

src/interceptors/fetch/index.ts
test/modules/fetch/intercept/fetch.request.browser.test.ts
test/modules/fetch/intercept/fetch.request.test.ts

The first argument passed to `fetch` may be a `Request` which will be used as the base of the second argument. E.g.,
```ts
const request = new Request('', { method: 'POST' });
fetch(request); // <- This is a POST fetch.
```
Parsing the request properties only from the second argument `init` will not cover this case.
We can parse from `ref` that is constructed from the native `Request` constructor here.
I haven't add test cases since I think it better to add after the test tool supports passing `Request`s.

fix(fetch): use native ref to parse request props

---

src/interceptors/ClientRequest/utils/cloneIncomingMessage.test.ts
src/interceptors/ClientRequest/utils/cloneIncomingMessage.ts

Fix #212 
The current implementation will clone the properties defined in `instance`.
But the `headers` property defined in `prototype` in Node.js v16 or higher.
So this PR aims to support prototype inheriting in `cloneIncomingMessage`.
> The final pitfalls is this is not support `instanceof IncomingMessage` and `instanceof PassThrough`. If the msw uses those operators,  I think this must not be merged.
Fixed.

fix(cloneIncomingMessage): inherit prototype properties

---

src/interceptors/ClientRequest/http.request.ts
src/interceptors/ClientRequest/utils/normalizeClientRequestArgs.test.ts
src/interceptors/ClientRequest/utils/normalizeClientRequestArgs.ts

- Fixes https://github.com/mswjs/msw/issues/1150
- The `options._defaultAgent` is now always set if it hasn't been explicitly provided. It's always set to the `<protocol>.globalAgent` as per [Node.js implementation](https://github.com/nodejs/node/blob/418ff70b810f0e7112d48baaa72932a56cfa213b/lib/_http_client.js#L130).
- Respective unit test added.

fix(ClientRequest): ensure "options._defaultAgent" is always set based on the protocol

---

src/interceptors/ClientRequest/NodeClientRequest.ts
test/features/events/request.test.ts
test/features/events/response.test.ts
test/modules/fetch/intercept/fetch.request.test.ts
test/modules/fetch/intercept/fetch.test.ts
test/modules/http/intercept/http.get.test.ts
test/modules/http/intercept/http.request.test.ts
test/modules/http/intercept/https.get.test.ts
test/modules/http/intercept/https.request.test.ts

- Originates from https://github.com/mswjs/msw/pull/1155
The `credentials` in `ClientRequest` are now always set to `same-origin`. That is to align with the same default value for `window.fetch`, which is often polyfilled via `ClientRequest`.
Note that `credentials` for `XMLHttpReqiest` remains intact: it depends on `.withCredentials`, which requires you to set it to `true` in order to achieve the `include` behavior.

feat(ClientRequest): set "credentials" to "same-origin"

---

src/interceptors/ClientRequest/utils/getIncomingMessageBody.test.ts
src/interceptors/ClientRequest/utils/getIncomingMessageBody.ts
test/features/events/response.test.ts

Fixes https://github.com/mswjs/interceptors/issues/222
- Make `getIncomingMessageBody` resolve its promise even if body is empty. (It hangs indefinitely in the current code.)

fix(getIncomingMessageBody): Make `getIncomingMessageBody` return on empty body

---

src/index.ts

The main classes of the libraries were not exported after the recent refactor.

fix: export "Interceptor", "BatchInterceptor" classes

---

src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
test/modules/XMLHttpRequest/response/xhr.test.ts

- Fixes #252
- Sets `this.responseURL` in XHR for mocked responses (previously `""`).
- Updates integration tests to assert for the `responseURL` value.

fix(XMLHttpRequest): set "responseURL" for mocked responses

---

src/BatchInterceptor.test.ts
src/RemoteHttpInterceptor.ts
src/interceptors/ClientRequest/NodeClientRequest.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
src/interceptors/fetch/index.ts
src/utils/AsyncEventEmitter.test.ts
src/utils/AsyncEventEmitter.ts
test/helpers.ts
test/jest.browser.config.js
test/modules/XMLHttpRequest/response/xhr-response-patching.browser.runtime.js
test/modules/XMLHttpRequest/response/xhr-response-patching.browser.test.ts
test/modules/fetch/response/fetch-response-patching.browser.test.ts
test/modules/fetch/response/fetch-response-patching.runtime.js
test/modules/fetch/response/fetch.browser.runtime.js
test/modules/fetch/response/fetch.browser.test.ts
test/modules/http/response/http-response-patching.test.ts

`emitter.untilIdle` awaited _all_ listeners for a certain event. When the listener resolution is nested, for example, like during response patching, this caused for `untilIdle` to never resolve, pending infinitely. 
```
- request A
- "request" listener (pending)
- request B (called within the "request" listener)
- "request" listener (the same)
- interceptor waits `untilIdle` but the listeners Promise state is:
[
// The first "request" listener that awaits the child requests
// to get resolved.
Promise<pending>,
// The child (nested) request. Cannot be resolved because it waits
// for the parent (first) request to be resolved. 
Promise<pending>
]
```

fix: ignore irrelevant request listeners during response patching

---

README.md

Without this `this` isn't defined.

docs: add "new" to BatchInterceptor calls

---

src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
src/utils/toIsoResponse.ts

Bumped into this in MSW, setting `ctx.status(0)` results in a `200` status in the mocked response. Guessing this change will more closely match the intent of the code since `status` is a `number`?

fix: support 0 as an explicit status code

---

package.json
src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
src/interceptors/XMLHttpRequest/utils/isDomParserSupportedType.ts
test/modules/XMLHttpRequest/compliance/xhr-response-body-xml.test.ts
yarn.lock

- Closes #297 
- `req.responseXML` will not rely on the native (global) `DOMParser`. It's present in the browser and it must be polyfilled in browser-like environments for XHR to work.

fix(xhr): removes @xmldom/xmldom, uses native DOMParser

---

src/Interceptor.test.ts
src/Interceptor.ts

`readyState` is a public property, thus a breaking change. 
- Fixes #302

feat: change "IDLE" ready state to "INACTIVE"

---

src/interceptors/fetch/index.ts

Useless information, polluting the console

fix(fetch): remove internal `console.log` statement

---

src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts
test/modules/XMLHttpRequest/intercept/XMLHttpRequest.browser.test.ts
test/modules/XMLHttpRequest/regressions/xhr-compressed-response.browser.test.ts
test/modules/XMLHttpRequest/regressions/xhr-compressed-response.test.ts

- Fixes #308 
Thank you so much for working on this project, it is immensely useful!
TLDR: I am using the browser interceptors on a site that is serving responses with `Content-Encoding: br` or `gzip` or `deflate` etc. This breaks every request since `Content-Encoding` is typically for compression algorithms, like `gzip`, like this site responds with, but `TextDecoder` takes a character encoding, like `utf-8`. This breaks every request even if nothing is done by the user because the library logs the response, which implicitly calls `responseText()`. Avoiding passing the `Content-Encoding` to `TextDecoder` fixes the issue.
---
Currently, the interceptors break on every request without me doing anything because the `loadend` event logs the `response` which implicitly calls `responseText()`: …

fix(xhr): do not pass response `Content-Encoding` to `TextDecoder`

---

src/interceptors/ClientRequest/NodeClientRequest.ts

- Closes #304 
- Related to https://github.com/mswjs/msw/issues/1515 
This should account for `NodeRequestClient.agent` being potentially undefined.

fix(NodeRequestClient): account for undefined "agent" when terminating a request

---

package.json
src/interceptors/ClientRequest/NodeClientRequest.ts
yarn.lock

Spotted that there's a race condition between the mocked response body finished reading the the NodeClientRequest emitting the "response" event, allowing the consumer to read the response body that may not be yet fully read in the interceptor.

fix(ClientRequest): fix race condition when emitting "response"

---

package.json

When compiling with webpack, it throws an error since the default was out of order:
using: 
`import { FetchInterceptor } from '@mswjs/interceptors/fetch'`
error:
```
Module not found: Error: Default condition should be last one
@ ./src/index.js 11:0-57 32:4-19
webpack 5.75.0 compiled with 1 error in 1012 ms
```

fix: place the default export for "fetch" last

---

src/utils/getUrlByRequestOptions.test.ts
src/utils/getUrlByRequestOptions.ts

- Fixes #353 
This should also make the URL resolution a bit faster in the case when `options.uri` is explicitly provided because we won't attempt to figure out URL parts from the options then.

fix: improve node.js host resolution

---

src/interceptors/fetch/index.ts
test/modules/fetch/fetch-exception.browser.test.ts
test/modules/fetch/fetch-exception.runtime.js
test/modules/fetch/fetch-exception.test.ts

- Fixes https://github.com/mswjs/msw/issues/1557
Since we now ship the fetch interceptor in the Node preset by default, we are mocking the `globalThis.fetch` function calls directly instead of tapping into the underlying `http.ClientRequest` as before. Previously, erroring the underlying client request bubbled to whichever fetch implementation the user was using, and that implementation faithfully handled those errors as `TypeError`.
Now, we become that fetch implementation (in the case of middleware exceptions) so we need to forward middleware exceptions as `TypeError` to the consumer.

fix(fetch): treat middleware exceptions as TypeError

---

src/interceptors/XMLHttpRequest/XMLHttpRequestController.ts
test/modules/XMLHttpRequest/compliance/xhr-event-handlers.test.ts
test/modules/XMLHttpRequest/compliance/xhr-timeout.test.ts

- Fixes #359
I still have 0 idea why JSDOM doesn't fire its setter for `onload`. It doesn't even have one. Narrowing down the workaround to concern itself only with `ontimeout`. All other event handlers seem to be working correctly (added tests).

fix(XMLHttpRequest): prevent event handlers from being called twice

---

src/interceptors/ClientRequest/utils/createRequest.test.ts
src/interceptors/ClientRequest/utils/createRequest.ts

Creating a GET or HEAD fetch Request with a non-null/undefined body throws a `TypeError`. Some (possibly misbehaving) clients (notably the Stripe Node library) write an empty string to the request buffer even for GET/HEAD, causing a failure when intercepting any of those requests.
A test has been added to `createRequest.test.ts` that fails without this change.

fix(ClientRequest): set null body for GET/HEAD requests

---

test/modules/XMLHttpRequest/regressions/xhr-0-status-code.test.ts

- Closes #336 
- Closes https://github.com/mswjs/interceptors/issues/335
This test confirms that even when the XHR errors (has `status: 0`), the library never attempts to construct a Fetch API Response out of it (causing the 200 599 range error).

test(xhr): add failed request integration test

---

src/interceptors/fetch/index.ts
test/modules/fetch/response/fetch-response-patching.browser.test.ts

Fixes #368
---
Makes aborting fetch requests consistent between patched and unpatched responses.

fix(fetch): respect AbortSignal during response patching

---

package.json
yarn.lock

- Fixes [this broken CI](https://github.com/mswjs/msw/actions/runs/4688831418/jobs/8321120998?pr=1436) where Jest failed to resolve `@open-draft/logger` because I opted out from the browser resolution in JSDOM. With 0.3.0, the logger comes with a single neutral build because it's API is universal anyway.

fix: update to "@open-draft/logger@0.3.0"

---

src/Interceptor.test.ts
src/Interceptor.ts
test/modules/http/compliance/http-req-write.test.ts

- `APPLIED` and `DISPOSED` interceptor state is now transitioned to _immediately_ (in the current event loop). 
I find it confusing that the interceptor is still showing `APPLYING` state when it's already applied. The patching logic affects the runtime as soon as it's invoked, so there is little reason to defer the interceptor's state transition to the next tick. If anything, it only results in confusing logs. 
This isn't a breaking change because nobody should rely on the internal ready state of the interceptors.

fix(Interceptor): set interceptor state on the current event loop cycle

---

src/interceptors/fetch/index.ts
test/modules/fetch/fetch-exception.browser.test.ts
test/modules/fetch/fetch-exception.test.ts

Fixes https://github.com/mswjs/interceptors/issues/381
Currently, when a network error is simulated in a response from `msw` server, as described in the [docs](https://mswjs.io/docs/api/response/network-error), (`return res.networkError('Failed to connect')), an error message with a stack trace appears in the console, although the tests would pass.
Here is an example of how this would look like to the developer who is using `msw`:
An error message, despite passing tests, is distracting. This PR removes the `console.error` statement responsible for this output.
When checked locally, this change cleaned up the test log:

fix(fetch): do not print console error on request failures

---

package.json
pnpm-lock.yaml
src/RemoteHttpInterceptor.ts
src/interceptors/ClientRequest/utils/createRequest.ts
src/interceptors/ClientRequest/utils/createResponse.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestController.ts
src/interceptors/XMLHttpRequest/utils/createResponse.ts
test/helpers.ts
test/modules/fetch/response/fetch-response-patching.browser.test.ts
test/modules/fetch/response/fetch.browser.test.ts

- Closes #406 
We can fully rely on the Fetch API `Headers` instead of using the `headers-polyfill` library.
We can substitute some of the utility functions of that library by `Array.from(headers.entries())`, and I've added a custom utility that converts `XMLHttpRequest.getAlLResponseHeaders()` string to a `Headers` instance (that one wasn't included in the polyfill library anyway).

feat: remove "headers-polyfill" dependency

---

test/modules/XMLHttpRequest/intercept/XMLHttpRequest.test.ts

I've noticed release job failures due to one integration test writing to `stderr` (not actually exiting): https://github.com/mswjs/interceptors/actions/runs/6018488102. 
This configures that test to correctly allow `credentials: "include" `in JSDOM through the right response header.

chore: set "Access-Control-Allow-Credentials" when testing xhr credentials

---

package.json

The package.json exports does not correctly export RemoteHttpInterceptor.

fix: package exports for "RemoteHttpInterceptor"

---

ossjs.release.config.js
package.json
pnpm-lock.yaml
release.config.json

The newest version of Release ships with improvements to streaming the stdio of the release process, which will help uncover what's going on in the Interceptor's release pipeline and why it fails.

chore: migrate to @ossjs/release 0.7.2

---

src/interceptors/ClientRequest/NodeClientRequest.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestProxy.ts
src/interceptors/fetch/index.ts
test/modules/XMLHttpRequest/response/xhr-response-error.browser.runtime.js
test/modules/XMLHttpRequest/response/xhr-response-error.browser.test.ts
test/modules/XMLHttpRequest/response/xhr-response-error.test.ts
test/modules/fetch/compliance/abort-conrtoller.test.ts
test/modules/fetch/compliance/fetch-response-error.test.ts
test/modules/fetch/fetch-exception.test.ts
test/modules/http/response/http-response-error.test.ts

- Closes #413 
- Prerequisite for https://github.com/mswjs/msw/pull/1730

feat: support "Response.error()" for mocking network errors

---

package.json
pnpm-lock.yaml

- Addresses failing browser ESM compatibility originating from `deferred-promise`.

fix: update @open-draft/deferred-promise to 2.2.0 (esm)

---

.github/workflows/release.yml

This repo used incorrect env variable for NPM auth token in case of PNPM.

chore: use "NODE_AUTH_TOKEN" env variable for pnpm publishing

---

package.json
yarn.lock

- Fixes incorrect minor release of a breaking change in https://github.com/mswjs/headers-polyfill/releases/tag/v3.3.0

fix: pin "headers-polyfill" to 3.2.5

---

tsconfig.json

Module resolution must be set to `NodeNext` if using `NodeNext` as the `module`.

chore: set "moduleResolution" to "NodeNext"

---

src/BatchInterceptor.test.ts
src/BatchInterceptor.ts
src/Interceptor.test.ts
src/Interceptor.ts
src/utils/AsyncEventEmitter.ts

- Adds `once` and `off` methods on the `Interceptor` class (and the derived classes, like `BatchInterceptor`) to attach one-time listener and to remove listener, respectively.

fix: add "once", "off", and "removeAllListeners" to the Interceptor class

---

package.json
pnpm-lock.yaml

- Related to #432 (fixes the wrapping of `.once()` listeners so they can be awaited).

fix: upgrade "strict-event-emitter" to 0.5.1

---

src/interceptors/ClientRequest/utils/createResponse.test.ts
src/interceptors/ClientRequest/utils/createResponse.ts
src/interceptors/XMLHttpRequest/utils/createResponse.ts
src/utils/responseUtils.ts
test/features/events/response.test.ts

fix(ClientRequest): ignore message body for responses without body

---

src/interceptors/ClientRequest/NodeClientRequest.ts
src/interceptors/ClientRequest/utils/createRequest.ts
src/utils/getUrlByRequestOptions.ts
test/modules/http/intercept/http.request.test.ts

Options: https://nodejs.org/api/http.html#httprequesturl-options-callback
@kettanaito 
* Not sure if this is where the test should be
* Also, I'm not sure if this is what you mean by "Do not propagate username and password onto the [NodeClientRequest.url](https://github.com/mswjs/interceptors/blob/b8bce893d7e9642a9836ad29a0903562dde7fbca/src/interceptors/ClientRequest/NodeClientRequest.ts#L71)", I just override the username/password. Please let me know if you have something else in mind.
closes #438

fix(ClientRequest): support the "auth" option

---

src/interceptors/ClientRequest/utils/normalizeClientRequestArgs.test.ts
src/interceptors/ClientRequest/utils/normalizeClientRequestArgs.ts
src/utils/isObject.ts
test/modules/http/intercept/http.request.test.ts

Currently, we ignore the path from the second argument.
@kettanaito 
When I do: 
```js
url.pathname = "/user?id=123"
```
It's automatically encodes it. Are we ok with this? see the `exepct` request.url line

fix(ClientRequest): respect "options.path" over "url.pathname"

---

src/interceptors/ClientRequest/utils/createRequest.test.ts
src/interceptors/ClientRequest/utils/createRequest.ts

According to [this test](https://github.com/nock/nock/blob/feaa66fa64d24f95937ef759cdd5a7ca07646f1c/tests/test_basic_auth.js#L34), passwords are not mandatory.
I couldn't find any specific spec for this, but I guess that if Nock has a test for it someone needed this.

fix(ClientRequest): support empty "username" and "password" basic auth values

---

src/interceptors/ClientRequest/utils/createRequest.test.ts
src/interceptors/ClientRequest/utils/createRequest.ts

Headers may be falsy:
Apply the same logic as in [`createResponse`](https://github.com/mswjs/interceptors/blob/main/src/interceptors/ClientRequest/utils/createResponse.ts#L41)

fix(ClientRequest): support falsy request headers

---

.github/workflows/ci.yml
src/interceptors/ClientRequest/NodeClientRequest.test.ts
src/interceptors/ClientRequest/NodeClientRequest.ts
src/utils/getRawFetchHeaders.test.ts
src/utils/getRawFetchHeaders.ts
src/utils/getValueBySymbol.test.ts
src/utils/getValueBySymbol.ts
test/modules/http/compliance/http-res-raw-headers.test.ts

There are a few typing issues, but I would like to hear what you think about this solution first.
Do you know how can we find the Symbol more elegantly? I'm not very familiar with Symbols and `Symbol.for('headers list')` returns `undefined`
closes #448 
----
Some thoughts:
1. While this solution probably will work for good, it relies on an "unofficial" behavior of Node.
2. Perhaps we could add a function that allows users to set the 'rawHeaders', although it may be a bit clumsy.
3. We can also solve it from Nock's side by sending a tempered version of the `Response` object which does not return lowercase headers. but IMO the solution should be in this lib.

fix(ClientRequest): preserve headers casing on mocked responses

---

src/interceptors/ClientRequest/NodeClientRequest.test.ts
src/interceptors/ClientRequest/NodeClientRequest.ts

I didn't add a test because we already tested this logic in the following:
1. emits the ENOTFOUND error connecting to a non-existing hostname given no mocked response
2. emits the ECONNREFUSED error connecting to an inactive server given no mocked response
closes #451

fix(ClientRequest): suppress "ENETUNREACH" socket error

---

src/interceptors/ClientRequest/NodeClientRequest.ts

- Related to #454 
When testing on Node.js 18.14.2, I get a different error from the `ENETUNREACH` test case:
```
[Error: connect EHOSTUNREACH 2607:f0d0:1002:51::4:80 - Local (:::59828)]
```
This may be related to different versions of Node.js. I'm adding the `EHOSTUNREACH` error to the list of suppressed errors as well.

fix(ClientRequest): suppress the "EHOSTUNREACH" connection error

---

src/interceptors/ClientRequest/utils/normalizeClientRequestArgs.ts
test/modules/http/compliance/http-request-without-options.test.ts

fix(ClientRequest): support "http.request()" and "http.get()" without any arguments

---

.github/workflows/release.yml

Addresses [failing release pipeline](https://github.com/mswjs/interceptors/actions/runs/6444001793) due to Node version-specific `Headers` tests.

chore(release): use node v18.14.x for release

---

src/Interceptor.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestController.ts
test/modules/XMLHttpRequest/compliance/xhr-event-callback-null.test.ts

When a XMLHttpRequest event handler is reset by setting it to `null`, an error will be thrown, that @mswjs/interceptors cannot access the property `name` on `null`. Here is an example of that error:
```ts
const req = new XMLHttpRequest()
req.onload = function() { console.log(`Responded with status %i`, this.status) }
req.ontimeout = null
req.open("GET", "http://localhost:7003/test/status/200")
req.send()
```
This PR prevents the error by not accessing the `name` property if the listener is `undefined | null`;
Do you think it needs tests, or is it fine as-is?

fix(XMLHttpRequest): prevent invalid listener name access

---

package.json
pnpm-lock.yaml
src/utils/createProxy.ts
test/modules/XMLHttpRequest/regressions/xhr-axios-xhr-adapter.test.ts

- Fixes https://github.com/mswjs/msw/issues/1816
This issue is caused by the Axios XHR adapter in Happy DOM only. Axios does:
```js
request.timeout = config.timeout
```
Where `request` is already a proxy established by Interceptors. It looks up the `setProperty` trap on the proxy and since `timeout` doesn't have a special case, it defaults to `invoke()`. 
Calling `invoke()` to set `timeout` on XMLHttpRequest proxy _returns false_ because property `timeout` does not exist on `target`:
https://github.com/mswjs/interceptors/blob/1f04d100bad190a393a5855fc6cc3a54f6117dfb/src/utils/findPropertySource.ts#L9-L11
The `timeout` property is not mandatory on XMLHttpRequest, so it's missing from the immediate XHR instance as well as its prototype. We return false from the setter and that causes the …

fix(xhr): allow setters for non-existing properties

---

src/interceptors/XMLHttpRequest/XMLHttpRequestController.ts
test/envs/react-native-like.ts
test/modules/XMLHttpRequest/regressions/xhr-location-undefined.test.ts
test/vitest.config.js

- Related to https://github.com/mswjs/msw/issues/1777
- The XHR interceptor will no longer blindly rely on the global `location` object because it may not be present in the environment that implements XHR (e.g. React Native).

fix(xhr): support environments with missing "location"

---

tsup.config.ts

Adds sourcemaps to the build. Remix relies on sourcemaps for ESM it loads and Interceptors doesn't provide any, breaking the server-side build of Remix.

fix: add sourcemaps

---

src/interceptors/fetch/index.ts
src/utils/canParseUrl.ts
test/modules/fetch/intercept/fetch-relative-url.test.ts

- Fixes https://github.com/mswjs/msw/issues/1625

fix: resolve relative fetch urls against location

---

package.json
pnpm-lock.yaml
src/interceptors/WebSocket/WebSocketClassTransport.ts
src/interceptors/WebSocket/WebSocketOverride.ts
src/interceptors/WebSocket/WebSocketServerConnection.ts
src/interceptors/WebSocket/utils/event.test.ts
src/interceptors/WebSocket/utils/events.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestController.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestProxy.ts
test/envs/node-with-websocket.ts
test/envs/react-native-like.ts
test/modules/WebSocket/exchange/websocket.server.connect.test.ts
test/modules/WebSocket/intercept/websocket.server.events.test.ts
test/modules/XMLHttpRequest/intercept/XMLHttpRequest.test.ts
test/modules/XMLHttpRequest/regressions/xhr-axios-xhr-adapter.test.ts
test/modules/fetch/intercept/fetch.request.test.ts
test/modules/fetch/intercept/fetch.test.ts
test/modules/http/intercept/http.get.test.ts
test/modules/http/intercept/https.get.test.ts
test/modules/http/regressions/http-socket-timeout.test.ts

- See https://github.com/nodejs/node/issues/51767

fix(WebSocket): make MessageEvent cancelable

---

src/interceptors/WebSocket/WebSocketClientConnection.ts
test/modules/WebSocket/compliance/websocket.connection.test.ts

When implementing broadcasting, there has to be an identifier for each client connection. The `client.id` string serves as the identifier. 
I believe that the Interceptors library should remain low-level. This means that higher-level features such as event broadcasting have to be implemented by higher-level libraries like MSW.

fix(WebSocket): add "client.id" property

---

src/interceptors/WebSocket/WebSocketOverride.ts

This way, imports to `WebSocketOverride` do not produce a dependency on the global `WebSocket` class. Otherwise, the `WebSocket.CONNECTING` (and similar) throw an error when you import the WebSocket interceptor, even if you are not planning on doing anything with it.
Context: getting the WebSocket undefined error when migrating to the latest Interceptors in MSW:
```
FAIL  src/browser/setupWorker/setupWorker.node.test.ts [ src/browser/setupWorker/setupWorker.node.test.ts ]
ReferenceError: WebSocket is not defined
❯ node_modules/.pnpm/@mswjs+interceptors@0.26.5/node_modules/@mswjs/interceptors/src/interceptors/WebSocket/WebSocketOverride.ts:22:32
```

fix(WebSocket): use literal values for ready state properties

---

README.md

Fixes `Property 'on' does not exist on type 'WebSocketClientConnection'.` and `Property 'on' does not exist on type 'WebSocketServerConnection'.` errors.

docs: fix WebSocketInterceptor usage example

---

src/interceptors/WebSocket/index.ts
test/modules/WebSocket/intercept/websocket.dispose.test.ts

Calling `.revoke()` on a revocable Proxy _does not restore its impementation_. I was wrong to assume that. It simply blows up the proxy object so _any object operations that result in a trap **throw**_. 
Also added a test to ensure that the restored `WebSocket` class is fully operational after the interceptor is disposed.

fix(WebSocket): reassign global to restore WebSocket

---

src/interceptors/WebSocket/index.ts
test/modules/WebSocket/compliance/websocket.connection.test.ts

Right now, the `connection` event is emitted to the interceptors on the same tick as the WebSocket instance is created. It makes it impossible to observe the changes to that instance while connecting. 
For example, the client may set a different `.binaryType` on the socket _after_ it's constructed (i.e. starts connecting):
```js
const socket = new WebSocket(url)
socket.binaryType = 'arraybuffer'
```
For the interceptor to know about that change, we have to emit the connection event on the next tick, when any modifications to the socket are complete (including the event listeners). 
This will allow us to properly inherit `.binaryType` on the real socket when calling `server.connect()`. This also gives us a behavior similar to production code, where the `open` event will always be emitted …

fix(WebSocket): emit "connection" event on the next tick

---

src/interceptors/WebSocket/WebSocketClientConnection.ts

I think it's a good idea to expose the original `WebSocket` instance on the `client` connection object. We also use it in MSW to add the `message` listeners for logging.

fix(ws): make "WebSocket" reference (client.socket) public

---

src/interceptors/WebSocket/index.ts

It's quite annoying to annotate the `client`/`server` types manually whenever you need them in collocation (e.g. when forwarding/handling the emitted `connection` event). Let's export it as-is.

fix(WebSocket): export "WebSocketConnectionData" type

---

src/interceptors/ClientRequest/MockHttpSocket.ts
src/interceptors/Socket/MockSocket.ts
test/modules/http/compliance/http-req-write.test.ts
test/modules/http/regressions/http-concurrent-same-host.test.ts

fix: support Readable as request body

---

README.md
src/interceptors/WebSocket/WebSocketServerConnection.ts
test/modules/WebSocket/compliance/websocket.server.close.test.ts
test/modules/WebSocket/utils/waitForWebSocketEvent.ts
test/modules/http/response/readable-stream.test.ts

Allows closing the actual server connection by adding a new `server.close()` method.

fix(WebSocket): add "server.close()" method

---

src/Interceptor.ts
src/interceptors/ClientRequest/NodeClientRequest.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestController.ts
test/modules/XMLHttpRequest/intercept/XMLHttpRequest.browser.test.ts

- Workaround for https://github.com/mswjs/msw/issues/1935
- Related to #378

fix: use internal request id header vs "X-Request-Id"

---

src/interceptors/WebSocket/WebSocketClientConnection.ts
src/interceptors/WebSocket/WebSocketOverride.ts
test/modules/WebSocket/compliance/websocket.client.events.test.ts

- Also annotates the accepted event types on `client.addEventListener()`/`client.removeEventListener()`. 
Allow the interceptor to listen to the WebSocket client close events because the client can close itself as well.

fix(WebSocket): forward "close" event to WebSocketClientConnection

---

src/interceptors/WebSocket/utils/bindEvent.ts
test/modules/WebSocket/compliance/websocket.client.events.test.ts
test/modules/WebSocket/compliance/websocket.events.test.ts

fix(WebSocket): set correct "currentTarget" on client events

---

test/modules/WebSocket/compliance/websocket.events.test.ts

Add the `currentTarget` assertions for WebSocket client instance tests.

test(ws): add "currentTarget" assertions on instance events

---

README.md
package.json
src/interceptors/WebSocket/WebSocketClassTransport.ts
src/interceptors/WebSocket/WebSocketClientConnection.ts
src/interceptors/WebSocket/WebSocketOverride.ts
src/interceptors/WebSocket/WebSocketServerConnection.ts
src/interceptors/WebSocket/WebSocketTransport.ts
test/modules/WebSocket/compliance/websocket.send.test.ts
test/modules/WebSocket/compliance/websocket.server.close.test.ts
test/modules/WebSocket/compliance/websocket.server.connect.test.ts
test/modules/WebSocket/exchange/websocket.server.connect.browser.test.ts
test/modules/WebSocket/exchange/websocket.server.connect.test.ts
test/modules/WebSocket/third-party/socket.io.browser.test.ts

- Implements https://github.com/mswjs/msw/discussions/2010#discussioncomment-9024640
Outgoing client messages are now forwarded to the actual server by default after `server.connect()` is called. To prevent this, call `event.preventDefault()` on the respective client message.

feat(WebSocket): forward client messages to the server by default

---

src/interceptors/WebSocket/utils/events.test.ts
src/interceptors/WebSocket/utils/events.ts

Without these setters, using `CancelableMessageEvent` in HappyDOM fails:
```
TypeError: Cannot set property defaultPrevented of #<CancelableMessageEvent> which has only a getter
❯ new Event node_modules/happy-dom/src/event/Event.ts:18:25
❯ new MessageEvent node_modules/happy-dom/src/event/events/MessageEvent.ts:25:3
❯ new CancelableMessageEvent node_modules/@mswjs/interceptors/src/interceptors/WebSocket/utils/events.ts:16:5
❯ WebSocketOverride.WebSocketClassTransport.socket.<computed> node_modules/@mswjs/interceptors/src/interceptors/WebSocket/WebSocketClassTransport.ts:40:13
❯ node_modules/@mswjs/interceptors/src/interceptors/WebSocket/WebSocketOverride.ts:140:3
❯ node:internal/process/task_queues:140:7
❯ AsyncResource.runInAsyncScope node:async_hooks:206:9
❯ AsyncResource.runMicrotask …
```

fix(CancelableMessageEvent): add setters for "cancelable" and "defaultPrevented"

---

src/interceptors/WebSocket/WebSocketClientConnection.ts
src/interceptors/WebSocket/WebSocketServerConnection.ts
src/interceptors/WebSocket/WebSocketTransport.ts
test/modules/WebSocket/compliance/websocket.client.events.test.ts

- Adds `this: WebSocket` annotation to client event listeners.
- Binds the client listeners to `this.socket`.
- Stores the bound listeners for both client and server in `kBoundListener` so the same bound listener can be referenced when you call `.removeEventListener()`.
> This also fixed a bug where you wouldn't be able to remove the listener once it's bound.

fix(WebSocket): reference bound listener when calling `.removeEventListener()`

---

.github/workflows/ci.yml
.github/workflows/release.yml
pnpm-lock.yaml

As an effort to migrate all my projects to pnpm 8, let's update Interceptors as well. 
- Related to #512

chore: use pnpm@8.15 on ci

---

package.json

in case of mixed environments that look for both
"node" and "browser" export conditions

fix: give `node` export condition higher priority

---

src/interceptors/ClientRequest/NodeClientRequest.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestProxy.ts
src/interceptors/fetch/index.ts
src/utils/responseUtils.ts
test/modules/XMLHttpRequest/compliance/xhr-middleware-exception.test.ts
test/modules/fetch/fetch-exception.test.ts
test/modules/http/compliance/http-unhandled-exception.test.ts

- If you throw a `Response` instance in a request listener, that instance will be used as a mocked response. 
- If you throw anything else, it will be coerced to a 500 error response, similar to how an actual server would handle an uncaught exception. 
> If you want to emulate a request error, do `request.respondWith(Response.error())`.

fix: unify server error response across interceptors

---

src/interceptors/ClientRequest/MockHttpSocket.ts
test/modules/http/compliance/http-ssl-socket.test.ts

Forwards the following TLS socket properties onto the `MockHttpSocket` (for both mocked and passthrough responses):
- `encrypted`
- `authorized`
- `getSession()`
- `getProtocol()`
- `isSessionReused()`

fix(MockHttpSocket): forward tls socket properties

---

src/interceptors/ClientRequest/MockHttpSocket.ts
test/modules/http/compliance/http-ssl-socket.test.ts

It seems like Node.js set these properties on `TLSSocket` init, before the `connect` event ([source](https://github.com/nodejs/node/blob/main/lib/_tls_wrap.js#L574)).
With umocked `https`:
```js
https.get('https://example.com')
.on('socket', socket => {
console.log(socket.authorized); // false
console.log(socket.encrypted);  // true
}); 
```

fix(MockHttpSocket): set tls socket properties on init

---

src/glossary.ts
src/interceptors/ClientRequest/NodeClientRequest.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestController.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestProxy.ts
src/interceptors/fetch/index.ts
test/modules/XMLHttpRequest/compliance/xhr-middleware-exception.test.ts
test/modules/fetch/fetch-exception.test.ts
test/modules/http/compliance/http-unhandled-exception.test.ts

- Related to https://github.com/mswjs/msw/pull/2135
Adds a new event to the HTTP events map called `unhandledException`. If the listener for that event is provided, whenever an unhandled exception occurs in the `request` listener, the `unhandledException` listener will be called (if present).
This allows the client to opt-out from the default handling of exceptions (producing 500 error responses), as well as do so conditionally. If the `unhandledException` listener does nothing, the default handling kicks in. 
**Note:** The `unhandledException` listener receives a _readonly_ `request` instance (non-interactive request). To affect the request, it receives an additional `controller` object with methods `.respondWith()` and `.errorWith()`. 
> `request.respondWith()` operates on a promise …

feat: add "unhandledException" event

---

src/interceptors/ClientRequest/utils/createRequest.ts
test/third-party/axios.test.ts

fix(ClientRequest): decode uri for username and password before setting basic authentication header

---

src/interceptors/WebSocket/WebSocketOverride.ts

This issue came up in #577, see that thread for more information.
The WebSocket specification uses an empty string if no protocol is agreed upon, not `ws`.

fix: set "WebSocket.protocol" to an empty string by default

---

README.md
src/interceptors/WebSocket/index.ts
test/modules/WebSocket/compliance/websocket.connection.test.ts

Currently, there is no way to access the full list of protocols supported by the WebSocket client. `WebSocketOverride` only exposes the first value ([relevant line](https://github.com/mswjs/interceptors/blob/main/src/interceptors/WebSocket/WebSocketOverride.ts#L54)).
This PR exposes the client protocols in the `connection` event, so tests can verify the client provided the right protocols.

feat(WebSocket): add connection "info" to the "connection" event payload

---

test/modules/http/compliance/http-event-connect.test.ts

test(http): add "connect" and "secureConnect" tests

---

src/interceptors/ClientRequest/NodeClientRequest.ts

Follow-up from https://github.com/mswjs/interceptors/pull/330, see https://github.com/mswjs/interceptors/issues/304#issuecomment-2178645901 for details.
I understand that this is all highly unfortunate. But as long as some agent providers misbehave, this does help. Thank you!

fix(ClientRequest): account for missing `agent.destroy` when terminating a request

---

src/interceptors/ClientRequest/NodeClientRequest.ts
test/features/events/response.test.ts
test/modules/http/response/http-await-response-event.test.ts

- Fixes #569 
- ClientRequest: Awaits all the `response` event listeners before finishing the response (emitting its `end` event). This affects both mocked and original responses (the approach is different for each).

feat(ClientRequest): await response listeners before emitting the "end" response event

---

.github/workflows/ci.yml
.github/workflows/release.yml

Looks like `pnpm/action-setup@v2` is reliably failing on CI: https://github.com/mswjs/interceptors/actions/runs/9785986585/job/27048245243

chore: update pnpm/action-setup to v4

---

src/interceptors/ClientRequest/NodeClientRequest.ts

The `.emit()` method must return a boolean indicating if the given event has any listeners. Do that in case we defer the `end` event too.

fix(ClientRequest): return correct boolean from `.emit()` proxy

---

src/interceptors/ClientRequest/MockHttpSocket.ts
test/modules/http/response/http-empty-response.test.ts
test/modules/http/response/http-response-transfer-encoding.test.ts

> Context: this allows us to support mocked responses with `Transfer-Encoding` and, potentially, other response transformations. 
I still need to give meaningful names to some variables, but it works as expected.
The idea here is that MSW acts as a Node.js server and uses the `ServerResponse` class to build the final chunks that we later push to our `socket`.
The only caveat I found is that we are maybe TOO close to the Node.js implementation 😅. For example, Nock's tests found that `ServerResponse` automatically returns `connection` and `date` headers, which we now add to the response. 
I think we can remove this default behavior, but I first want to know how you see it.
@kettanaito

fix(ClientRequest): use `ServerResponse` to build the HTTP response string

---

src/interceptors/ClientRequest/MockHttpSocket.ts
src/interceptors/ClientRequest/index.test.ts
test/modules/http/compliance/http-res-destroy.test.ts

fix(ClientRequest): destroy socket when destroying IncomingMessage

---

src/interceptors/ClientRequest/index.test.ts
src/interceptors/ClientRequest/utils/recordRawHeaders.test.ts
src/interceptors/ClientRequest/utils/recordRawHeaders.ts
test/modules/http/compliance/http-res-raw-headers.test.ts

@kettanaito The [problem](https://github.com/mswjs/interceptors/pull/598#discussion_r1671313975) was that we didn't unset the `kRestorePatches` symbol on `dispose`
I think my solution may not be "private" enough because I set it to be `configurable`. Alternatively, we can conditionally return undefined by toggling a variable, but it's smelly and error-prone. 
What is the best solution here?

fix(ClientRequest): improve rawHeaders recording

---

src/interceptors/WebSocket/WebSocketOverride.ts
src/interceptors/WebSocket/index.ts
test/modules/WebSocket/compliance/websocket.client.events.test.ts
test/modules/WebSocket/compliance/websocket.close.test.ts
test/modules/WebSocket/compliance/websocket.events.test.ts
test/modules/WebSocket/compliance/websocket.protocol.test.ts
test/modules/WebSocket/compliance/websocket.server.connect.test.ts
test/modules/WebSocket/compliance/websocket.server.events.test.ts
test/modules/WebSocket/compliance/websocket.setters.test.ts
test/modules/WebSocket/intercept/websocket.send.browser.test.ts
test/modules/WebSocket/intercept/websocket.send.test.ts

> [!WARNING]
> Since WebSocket connections will now be established as-is if you haven't provided any interceptors, this is technically a breaking change despite fixing a bug. 
Interceptors has a bug that it will always emit the `open` even on the WebSocket client, even when there are no interceptor set up for any connections (so the connection cannot physically be intercepted). This results in such connections pending forever. 
> This may be a big against previously established expectations of WebSocket interception always being mock-first. But this is still a bug for bypassed connections, and it has to be fixed. 
I'm fixing this here without breaking any previously established promises. 
- WebSocket connection will be mock-first if _at least one `connection` listener on the interceptor …

feat(WebSocket): support passthrough, correctly emit the `error` event

---

src/interceptors/WebSocket/index.ts
test/modules/WebSocket/exchange/websocket.interceptor.exception.test.ts

- Related to https://github.com/mswjs/msw/pull/2011
While testing the `onUnhandledException` event in MSW, I noticed that unhandled exceptions in the `connection` listener are thrown on the entire process and are uncatchable. That's caused by the `connection` event being emitted in the `queueMicrotask` in the WebSocket interceptor. The queuing itself is correct.
I'm solving this by catching those interceptor exceptions and translating them to WebSocket connection closure with error. This means an unhandled interceptor exception will trigger `error` and `close` events, and also print the caught error to stderr.

fix(WebSocket): treat interceptor exceptions as closures with error

---

src/interceptors/WebSocket/index.ts
test/modules/WebSocket/exchange/websocket.interceptor.exception.test.ts

Using `1000` as a close code for when the connection must be terminated non-gracefully is incorrect. 
I believe 1011 suits the best for this scenario:
> 1011
>
>  1011 indicates that a server is terminating the connection because
>  it encountered an unexpected condition that prevented it from
>  fulfilling the request.
>

fix(WebSocket): use 1011 as close `code` for unhandled interceptor errors

---

test/helpers.ts
test/modules/XMLHttpRequest/intercept/XMLHttpRequest.browser.test.ts
test/modules/XMLHttpRequest/response/xhr.browser.test.ts

- Fixes #338 
- Closes #108
This adds browser tests for synchronous XMLHttpRequest. Both interception and mocking tests are passing in the browser as-is. I suspect the interceptor's rewrite to Proxy might have accidentally fixed the synchronous mode support. 
> [!IMPORTANT]
> Note that JSDOM doesn't seem to support synchronous XMLHttpRequests. The test hangs indefinitely if I do `request.open(method, url, false)`.

test(XMLHttpRequest): synchronous mode support

---

src/interceptors/fetch/index.ts
src/interceptors/fetch/utils/createNetworkError.ts
src/interceptors/fetch/utils/followRedirect.ts
src/utils/responseUtils.ts
test/modules/fetch/compliance/fetch-follow-redirects.test.ts
test/modules/fetch/compliance/fetch-request-body-used.test.ts

> [!WARNING]
> Marking this as a breaking (feat) release because mocked redirect responses will now be followed by default (previously, returned as-is). The previous behavior was faulty and not spec-compliant, but I don't want to break consumers once again. 
- Fixes #626 
- Fixes https://github.com/mswjs/msw/issues/2266
- Related to #575 
The redirect response handling is taken from Undici almost as-is because it doesn't export its `web/fetch/utils` as a typed module (it's untyped CJS). Luckily, Undici follows the spec in those implementations so they are unlikely to change. I'm also omitting things that are exclusive to Undici, such as accessing `request.body.source`. 
- https://github.com/nodejs/undici/blob/a6dac3149c505b58d2e6d068b97f4dc993da55f0/lib/web/fetch/index.js#L1173
- …

feat(fetch): support following redirect responses

---

src/interceptors/fetch/utils/followRedirect.ts
test/modules/fetch/compliance/fetch-follow-redirects.test.ts

Should we add a comment to explain why we use `request.url` as a base?

fix(fetch): rebase relative redirect URL against `request.url`

---

src/interceptors/XMLHttpRequest/XMLHttpRequestController.ts
test/modules/XMLHttpRequest/regressions/xhr-request-body-length.test.ts

- Fixes #630
The root cause of the issue is that cloning the Request to calculate the `Content-Length` header occurs too late. At the point in which clone() is called, the body buffer has already been consumed, so cloning fails.
Since this `kFetchRequest` value is only used for this specific purpose of calculating content-length, there is no harm in creating and storing a clone immediately upon creation of the Request object.

fix(xhr): clone the request before calculating its body size

---

src/interceptors/ClientRequest/agents.ts
test/modules/http/compliance/http-custom-agent.test.ts

When an intercepted request is not handled (`interceptor.on('request'...`) and the request uses a custom HTTP Agent, the custom agent's `createConnection` method is bound to the `MockHttpAgent`'s this context instead of the custom agent's this context, so methods/local variables are unavailable causing an exception.
This PR binds `this.customAgent` instead of the `MockAgent`'s `this` to the `createConnection` function to ensure scope is correct.
Fixes #635

fix(ClientRequest): fix a custom agent context in `createConnection`

---

src/interceptors/ClientRequest/utils/recordRawHeaders.ts

- Fixes https://github.com/mswjs/msw/issues/2281
- Fixes https://github.com/mswjs/msw/issues/2276

fix(ClientRequest): use `Object.defineProperty` when recording raw headers

---

src/interceptors/ClientRequest/utils/recordRawHeaders.test.ts
src/interceptors/ClientRequest/utils/recordRawHeaders.ts

- Related to https://github.com/mswjs/msw/issues/2290
- `recordRawHeaders`: properly records raw headers for `Request` that's been used as init for another `Request`. Also adds raw headers merging in case either of the requests have any raw headers recorded.

fix(ClientRequest): spy on `request.headers` used as init for request

---

src/interceptors/ClientRequest/utils/recordRawHeaders.test.ts
src/interceptors/ClientRequest/utils/recordRawHeaders.ts

- Fixes https://github.com/mswjs/msw/actions/runs/10956113682/job/30421449419?pr=2293
- Add handling for situations when a `Headers` instance has been constructed _before_ the interceptor started recording the raw headers. Previously, threw this error:
```
TypeError: inferRawHeaders(...) is not iterable (cannot read property undefined)
```
> We were trying to `...inferRawHeaders()` on a `Headers` instance that had no `kRawHeaders` symbol set (the recording hasn't started yet).

fix(ClientRequest): handle `Headers` without internal symbol

---

src/interceptors/WebSocket/WebSocketServerConnection.ts
test/modules/WebSocket/compliance/websocket.server.close.test.ts
test/modules/WebSocket/compliance/websocket.server.connect.test.ts
test/modules/WebSocket/compliance/websocket.server.socket.test.ts
test/modules/WebSocket/exchange/websocket.server.connect.test.ts

Makes the raw `socket` instance access consistent across `client.socket` and `server.socket`. Also drops `server.readyState` getter in favor of `server.socket.readyState` (`-1` as a value no longer a thing).

feat(ws): add "socket" property on `server` object

---

src/interceptors/WebSocket/WebSocketServerConnection.ts

MSW proxies the `server.send()` method to log a message whenever _the user_ is sending something from the mock to the server. But since Interceptors also call `server.send()` during the message forwarding, the logs display an entry as if the user has called `server.send()`.
Fix this by wrapping the send mechanism in a private method and calling _that_ private method during the forwarding.

fix(WebSocket): do not call public "server.send()" in message forwarding

---

src/interceptors/WebSocket/WebSocketOverride.ts
test/modules/WebSocket/compliance/websocket.reuse-listeners.test.ts
test/modules/WebSocket/exchange/websocket.readystate.test.ts
test/modules/WebSocket/utils/waitForNextTick.ts

This change prevents the WebSocket client from dispatching the open event if the connection has been rejected (closed/errored) in the connection event listener. 
Note that this keeps the oddity of the `client.socket.readtyState` being CONNECTING in the connection event listener. This isn't how an actual server connection event behaves, but this is necessary for the interceptor to reject the connection from within before it's ever opened (think of MSW rejecting the WebSocket connection if it's unhandled). 
During play testing, I've discovered that `client.socket.readyState` value was `0` (CONNECTING) in the connection event listener's scope. I believe that's incorrect. The `readyState` of the intercepted client MUST be `1` (OPEN) in the connection event listener. 
The connection event is …

fix(WebSocket): prevent dispatching "open" event if the connection was closed

---

src/interceptors/WebSocket/WebSocketServerConnection.ts
test/modules/WebSocket/compliance/websocket.server.events.test.ts

Fixes the issue where the forwarding of the "error" event of the original server couldn't be prevented by calling `event.preventDefault()`.

fix(WebSocket): make server "error" event cancelable

---

src/interceptors/fetch/index.ts
test/modules/fetch/response/fetch-await-response-event.test.ts
test/modules/http/response/http-await-response-event.test.ts

1. Added tests
2. wait for fetch unlocked request
3. reduce the sleep for the `ClientRequest` tests :) 
closes #656
@kettanaito Is it OK for the [`then` callback to be `async`](https://github.com/mswjs/interceptors/pull/658/files#diff-4593f50c24857397e849d8d6618757914a847fa2642a22bfaa3b703e15cb4969R147)?

fix(fetch): await response listener before resolving the response promise

---

src/utils/hasConfigurableGlobal.test.ts
src/utils/hasConfigurableGlobal.ts

fix: https://github.com/mswjs/interceptors/issues/668

fix(hasConfigurableGlobal): handle existing globals with undefined value

---

src/utils/handleRequest.ts
test/modules/fetch/compliance/abort-conrtoller.test.ts

- Related to https://github.com/mswjs/msw/issues/2314
The `handleRequest` function will now correctly handle intercepted requests where `request.signal.aborted` is `true`. Previously, it only added the listener for the `abort` event, but if the request has already been aborted by the time it's made, that event was never dispatched.

fix: support already aborted requests

---

src/interceptors/WebSocket/WebSocketClassTransport.ts
test/modules/WebSocket/compliance/websocket.client.send.test.ts
test/modules/WebSocket/compliance/websocket.connection.test.ts
test/modules/WebSocket/intercept/websocket.dispose.test.ts
test/modules/WebSocket/intercept/websocket.send.test.ts
test/modules/WebSocket/intercept/websocket.server.events.test.ts

When fixing the tests for our Socket.IO bunding, I've discovered that `client.send()` dispatches the message event on the WebSocket client immediately. If the client connection is still `CONNECTING` at the point, the message will be lost. 
- `client.send()` schedules data send for once the connection is open if it's not yet.
- `client.send()` does nothing if the connection is `CLOSING` or `CLOSED`.

fix(WebSocket): buffer sending the data until connection is open

---

src/interceptors/ClientRequest/MockHttpSocket.ts
test/modules/http/compliance/http-req-write.test.ts

- Fixes #684 
- Related to #674 
- Related to https://github.com/mswjs/msw/issues/2326
During the `flushWriteBuffer()`, set the invoked callback on the write args to `undefined` so it doesn't get called again (twice) during passthrough of requests that call `request.end()` within the `request.write()` callback. The issue is only reproducible in that scenario and doesn't happen on sequential write/end calls.

fix(ClientRequest): prevent `req.write()` callbacks from being called twice on passthrough

---

src/interceptors/ClientRequest/agents.ts
src/interceptors/XMLHttpRequest/utils/createEvent.ts

when running `npm run start` (which runs `tsc ...`) it reports errors due to missing or incorrect return types:
This PR fixes it so `tsc` passes.

fix(MockAgent): add explicit return types to agent methods

---

src/interceptors/ClientRequest/utils/recordRawHeaders.test.ts
src/interceptors/ClientRequest/utils/recordRawHeaders.ts

fix(ClientRequest): prevent `rawHeaders` from being shared across instances

---

src/interceptors/ClientRequest/agents.ts
src/interceptors/ClientRequest/utils/normalizeClientRequestArgs.test.ts
src/interceptors/ClientRequest/utils/normalizeClientRequestArgs.ts
test/modules/http/compliance/http-custom-agent.test.ts

resolves: https://github.com/nock/nock/issues/2828

fix(ClientRequest): pass custom agent options in passthrough

---

src/interceptors/ClientRequest/MockHttpSocket.ts
src/utils/fetchUtils.ts
test/features/events/response.test.ts
test/modules/fetch/compliance/fetch-response-url.test.ts

- Follows #695 
- Fixes #690
- Related to https://github.com/nock/nock/issues/2821
Our Fetch API representation of the response now sets `response.url` value correctly. 
If working with Undici, instead of redefining the `url` property, it grabs the response internal state and pushes a new entry to its `urlList`. This way, Interceptors doesn't interfere with Undici's `url` getter on the response, which is implemented per spec.
> Also per spec, `response.url` will be `''` if the `Response` instance was constructed manually, which is the case for Interceptors. During regular requests, the response `urlList` becomes a clone of the request's `urlList` (see [this](https://github.com/nodejs/undici/blob/981636f5fb882ff684c11177a3bfc8b1cf061f3a/lib/web/fetch/index.js#L1598)). We cannot do that, so …

fix(fetch): update `response.url` correctly

---

package.json
pnpm-lock.yaml

See https://github.com/mswjs/interceptors/pull/710#issuecomment-2805495148 for context.
From my local testing, the JSDOM dependency wasn't used at all. I ran the tests with both node v18 and node v22.
Note that my `pnpm-lock.yaml` has some more changes, probably coming from my version of pnpm (I just installed it). Tell me if you'd like me to use a specific version of pnpm. I also added `pnpm-workspace.yaml` to the `.gitignore` file because it appeared after installing packages. Happy to remove this change if you think it shouldn't be there.
Tell me what you think!

fix: remove `jsdom` from `dependencies`

---

src/interceptors/WebSocket/WebSocketClientConnection.ts
src/interceptors/WebSocket/WebSocketServerConnection.ts
src/interceptors/WebSocket/index.ts

Add the `WebSocketServerConnectionProtocol` type and annotate the `WebSocketConnectionData` `server` property using that type. This way, the consumer might implement the `server` property in any way they see fit (e.g. by using Playwright's `page.routeWebSocket()`) and still remain functional with the interceptor and the contract it introduces.
Also adds missing `addEventListener()` and `removeEventListener()` methods on both client and server protocols.
Also makes client and server protocols _abstract classes_.
Also exports previously missing event maps for client and server events so consumers can implement type-safe client and server protocols.

feat(WebSocket): implement `WebSocketServerConnectionProtocol`

---

src/interceptors/WebSocket/index.ts

- #726 introduced a regression where the `client` and `server` properties of the `connection` event were not implemented correctly. Despite internal client and server implementing their respective protocols, those objects _contain additional properties_, and the consumer must know about them, too.

fix(WebSocket): use non-protocol types for `client` and `server`

---

_http_common.d.ts
src/interceptors/ClientRequest/MockHttpSocket.ts
test/modules/http/compliance/http-custom-agent.test.ts
test/modules/http/compliance/http-max-header-fields-count.test.ts

- Fixes #729
- Closes #730
Adds the `kOnHeaders` internal callback to make sure we're buffering the request headers for "slow" requests correctly. 
> [!IMPORTANT]
> In the test case for multiple slow requests, I've somehow reproduced socket's `path` being `undefined`. That produces `/undefined` in the URL path so I'm adding a fallback to an empty string if that ever happens. This is not reproducible in isolation.

fix(ClientRequest): support intercepting "slow" requests

---

_http_common.d.ts
src/interceptors/ClientRequest/MockHttpSocket.ts
test/modules/http/compliance/http-max-header-fields-count.test.ts

Fixes #729
This is a follow-up to the previous PR #734 that addressed request header buffering for "slow" requests. While that PR focused on ensuring request headers are buffered correctly, this change extends the same validation to response headers to maintain consistency in header handling throughout the interceptor.

fix(ClientRequest): support mocking responses with a lot of headers

---

README.md
src/Interceptor.test.ts
src/interceptors/ClientRequest/MockHttpSocket.ts
src/interceptors/ClientRequest/utils/getIncomingMessageBody.test.ts
src/interceptors/ClientRequest/utils/normalizeClientRequestArgs.ts
src/interceptors/ClientRequest/utils/recordRawHeaders.test.ts
src/interceptors/ClientRequest/utils/recordRawHeaders.ts
src/interceptors/WebSocket/WebSocketOverride.ts
src/interceptors/XMLHttpRequest/XMLHttpRequestController.ts
src/interceptors/XMLHttpRequest/utils/createResponse.ts
src/utils/emitAsync.ts
test/modules/WebSocket/compliance/websocket.reuse-listeners.test.ts
test/modules/WebSocket/intercept/websocket.send.test.ts
test/modules/XMLHttpRequest/response/xhr.test.ts
test/modules/fetch/compliance/fetch-response-non-configurable.test.ts
test/modules/http/compliance/http-errors.test.ts
test/modules/http/compliance/http-max-header-fields-count.test.ts
test/modules/http/compliance/http-request-without-options.test.ts

Apply typo corrections across the codebase
Chores:
- Fix misspelled identifiers and function names (e.g., listners→listeners, createHeadersFromXMLHttpReqestHeaders→createHeadersFromXMLHttpRequestHeaders)
- Correct typos in comments and documentation (e.g., acommodate→accommodate, triggerring→triggering, internal, should)
- Fix spelling errors in test descriptions and identifiers across WebSocket, HTTP, fetch, and XHR tests

chore: various typos across codebase
